language: node_js

node_js:
  - "14"
  - "12"
install:
  - npm i

script:
  - npm run lint:ci
  - npm run build
  - npm run test:cov

after_success:
  - npm run report
  
notifications:
  email:
    on_success: never
    on_failure: always